[package]
name = "rust-tor-controller"
version = "0.1.0"
authors = ["Dhole <dhole@openmailbox.org>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
regex = "0.1"
rustc-serialize = "0.3"
rust-crypto = "^0.2"
