[package]
name = "tor_controller"
version = "0.1.0"
authors = ["Dhole <dhole@openmailbox.org>"]

[dependencies]
log = "~0.4"
env_logger = "~0.7"
regex = "1"
hex = "~0.4"
rust-crypto = "^0.2"
rand = "~0.7"
timer = "~0.2"
chrono = "~0.4"
